=== linancn/TianGong-LCA-Data/schemas/ILCD_Categories.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ILCD Format Version 1.1 Schemas Build 983 -->
<!--
Copyright (c) 1995-2009, European Commission. All rights reserved.

This file is part of the ILCD data format. The license conditions for the ILCD data format can be
found in the file ILCD_format_and_editor_license.txt included in this distribution. The license is
also available at http://lca.jrc.ec.europa.eu/eplca/doc/ILCD_format_and_editor_license.txt.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://lca.jrc.it/ILCD/Categories"
           xmlns:categories="http://lca.jrc.it/ILCD/Categories"
           xmlns:common="http://lca.jrc.it/ILCD/Common"
           version="1.1"
           targetNamespace="http://lca.jrc.it/ILCD/Categories"
           elementFormDefault="qualified">
   <xs:import schemaLocation="ILCD_Common_Groups.xsd"
              namespace="http://lca.jrc.it/ILCD/Common"/>
   <xs:complexType name="CategoryType">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
         <xs:element name="category" type="CategoryType"/>
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:anyAttribute namespace="##other" processContents="lax"/>
   </xs:complexType>
   <xs:complexType name="CategoriesType">
      <xs:sequence>
         <xs:element name="category" type="CategoryType" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="dataType" type="categories:DataSetType" use="required"/>
   </xs:complexType>
   <xs:complexType name="CategorySystemType">
      <xs:sequence>
         <xs:element name="referenceToSource" type="common:GlobalReferenceType" minOccurs="0"/>
         <xs:element name="categories" type="categories:CategoriesType" maxOccurs="7"/>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
   </xs:complexType>
   <xs:element name="CategorySystem" type="categories:CategorySystemType"/>
   <xs:simpleType name="DataSetType">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Process"/>
         <xs:enumeration value="LCIAMethod"/>
         <xs:enumeration value="Flow"/>
         <xs:enumeration value="FlowProperty"/>
         <xs:enumeration value="UnitGroup"/>
         <xs:enumeration value="Source"/>
         <xs:enumeration value="Contact"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>

=== linancn/TianGong-LCA-Data/stylesheets/ILCDFlowCategorization_Reference.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ILCD Format Version 1.1 Tools Build 1020 -->
<CategorySystem name="ILCD" xmlns="http://lca.jrc.it/ILCD/Categories" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://lca.jrc.it/ILCD/Categories ../schemas/ILCD_Categories.xsd">
  <categories dataType="Flow">
    <category id="1" name="Emissions">
      <category id="1.1" name="Emissions to water">
        <category id="1.1.1" name="Emissions to fresh water"/>
        <category id="1.1.2" name="Emissions to sea water"/>
        <category id="1.1.3" name="Emissions to water, unspecified"/>
        <category id="1.1.4" name="Emissions to water, unspecified (long-term)"/>
      </category>
      <category id="1.2" name="Emissions to soil">
        <category id="1.2.1" name="Emissions to agricultural soil"/>
        <category id="1.2.2" name="Emissions to non-agricultural soil"/>
        <category id="1.2.3" name="Emissions to soil, unspecified"/>
        <category id="1.2.4" name="Emissions to soil, unspecified (long-term)"/>
      </category>
      <category id="1.3" name="Emissions to air">
        <category id="1.3.1" name="Emissions to urban air close to ground"/>
        <category id="1.3.2" name="Emissions to non-urban air or from high stacks"/>
        <category id="1.3.3" name="Emissions to lower stratosphere and upper troposphere"/>
        <category id="1.3.4" name="Emissions to air, unspecified"/>
        <category id="1.3.5" name="Emissions to air, unspecified (long-term)"/>
      </category>
    </category>
    <category id="2" name="Resources">
      <category id="2.1" name="Resources from ground">
        <category id="2.1.1" name="Non-renewable material resources from ground"/>
        <category id="2.1.2" name="Non-renewable element resources from ground"/>
        <category id="2.1.3" name="Non-renewable energy resources from ground"/>
        <category id="2.1.4" name="Renewable element resources from ground"/>
        <category id="2.1.5" name="Renewable energy resources from ground"/>
        <category id="2.1.6" name="Renewable material resources from ground"/>
        <category id="2.1.7" name="Renewable resources from ground, unspecified"/>
        <category id="2.1.8" name="Non-renewable resources from ground, unspecified"/>
      </category>
      <category id="2.2" name="Resources from water">
        <category id="2.2.1" name="Non-renewable material resources from water"/>
        <category id="2.2.2" name="Non-renewable element resources from water"/>
        <category id="2.2.3" name="Non-renewable energy resources from water"/>
        <category id="2.2.4" name="Renewable element resources from water"/>
        <category id="2.2.5" name="Renewable energy resources from water"/>
        <category id="2.2.6" name="Renewable material resources from water"/>
        <category id="2.2.7" name="Renewable resources from water, unspecified"/>
        <category id="2.2.8" name="Non-renewable resources from water, unspecified"/>
      </category>
      <category id="2.3" name="Resources from air">
        <category id="2.3.1" name="Non-renewable material resources from air"/>
        <category id="2.3.2" name="Non-renewable element resources from air"/>
        <category id="2.3.3" name="Non-renewable energy resources from air"/>
        <category id="2.3.4" name="Renewable element resources from air"/>
        <category id="2.3.5" name="Renewable energy resources from air"/>
        <category id="2.3.6" name="Renewable material resources from air"/>
        <category id="2.3.7" name="Renewable resources from air, unspecified"/>
        <category id="2.3.8" name="Non-renewable resources from air, unspecified"/>
      </category>
      <category id="2.4" name="Resources from biosphere">
        <category id="2.4.1" name="Renewable element resources from biosphere"/>
        <category id="2.4.2" name="Renewable energy resources from biosphere"/>
        <category id="2.4.3" name="Renewable material resources from biosphere"/>
        <category id="2.4.4" name="Renewable genetic resources from biosphere"/>
        <category id="2.4.5" name="Renewable resources from biosphere, unspecified"/>
      </category>
    </category>
    <category id="3" name="Land use">
      <category id="3.1" name="Land occupation"/>
      <category id="3.2" name="Land transformation"/>
    </category>
    <category id="4" name="Other elementary flows"/>
  </categories>
</CategorySystem>
